version: 2.1
orbs:
  git-shallow-clone: guitarrapc/git-shallow-clone@2.0.3
jobs:
  build:
    machine:
      image: ubuntu-2004:202111-01
      docker_layer_caching: true
    working_directory: ~/repo
    steps:
      - git-shallow-clone/checkout
      - run: DEBIAN_FRONTEND=noninteractive sudo apt-get update 
      - run: DEBIAN_FRONTEND=noninteractive sudo apt-get install --no-install-recommends -qq -y awscli
      - run:
          name: Restart Docker with experimental features enabled
          command: |
            sudo sh -c 'echo '\''{"experimental": true}'\'' >> /etc/docker/daemon.json'
            sudo service docker restart
      - run:
          name: Check docker is running
          command: docker info
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: git submodule update --init --recursive
      - run:
          command: chmod +x ./build-with-docker.sh && ./build-with-docker.sh
          no_output_timeout: 30m
      - run: cd wasm/packages/core && tar czf ffmpeg.wasm-core.tar.gz dist/ && aws s3 cp ffmpeg.wasm-core.tar.gz s3://bunch-software-components/ffmpeg.wasm-core.tar.gz
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - feature/no-pthreads