version: 2.1
jobs:
  build_docker:
    machine:
      image: ubuntu-2004:202111-01
      docker_layer_caching: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Restart Docker with experimental features enabled
          command: |
            sudo sh -c 'echo '\''{"experimental": true}'\'' >> /etc/docker/daemon.json'
            sudo service docker restart
      - run:
          name: Check docker is running
          command: docker info
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: git submodule update --init --recursive
      - run:
          command: chmod +x ./build-with-docker.sh && ./build-with-docker.sh
          no_output_timeout: 30m
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - feature/no-pthreads